version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.28.Final
    - 5.4.30.Final
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.4
  - dependency-name: org.springframework.cloud:spring-cloud-starter-openfeign
    versions:
    - 3.0.2
  - dependency-name: com.github.ben-manes.caffeine:caffeine
    versions:
    - 3.0.1
  - dependency-name: org.apache.avro:avro-maven-plugin
    versions:
    - 1.10.2
  - dependency-name: org.apache.avro:avro
    versions:
    - 1.10.2
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - 2020.0.2
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework.hateoas:spring-hateoas
    versions:
    - 1.2.4
    - 1.2.5
  - dependency-name: org.springframework:spring-tx
    versions:
    - 5.3.4
    - 5.3.5
  - dependency-name: org.keycloak.bom:keycloak-adapter-bom
    versions:
    - 12.0.3
  - dependency-name: org.keycloak:keycloak-spring-boot-starter
    versions:
    - 12.0.3
  - dependency-name: org.keycloak:keycloak-spring-security-adapter
    versions:
    - 12.0.3
  - dependency-name: io.confluent:kafka-avro-serializer
    versions:
    - 6.1.0
  - dependency-name: org.hibernate.validator:hibernate-validator
    versions:
    - 7.0.0.Final
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
