spring:
  application:
    name: "EUREKA_SERVER"
  profiles:
    active: prod

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost