spring:
  application:
    name: "POSTS-SERVICE"
  main:
    web-application-type: servlet
  profiles:
    active: prod
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true

furrify:
  limits:
    posts: ${FURRIFY_LIMITS_POSTS:10000}
    media: ${FURRIFY_LIMITS_MEDIA:50000}
    attachments: ${FURRIFY_LIMITS_ATTACHMENTS:50000}