eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  application:
    name: "GATEWAY-SERVICE"
  cloud:
    gateway:
      routes:
        - id: postsService
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/users/*/posts/**
        - id: tagsService
          uri: lb://TAGS-SERVICE
          predicates:
            - Path=/users/*/tags/**
        - id: artistsService
          uri: lb://ARTISTS-SERVICE
          predicates:
            - Path=/users/*/artists/**

server:
  port: 8080