spring:
  application:
    name: "TAGS-SERVICE"
  main:
    web-application-type: servlet
  profiles:
    active: prod
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true


furrify:
  limits:
    tags: ${FURRIFY_LIMITS_TAGS:1000}