logging:
  level:
    web: DEBUG

spring:
  kafka:
    bootstrap-servers: http://192.168.1.200:9092
    schema-registry-servers: http://192.168.1.200:8081
    consumer:
      group-id:
        prefix: "tags-test-"
    producer:
      retries: 3
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid
            authorization-grant-type: authorization_code
            client-id: furrifyws-storage
        provider:
          keycloak:
            issuer-uri: https://keycloak.furrify.tech/realms/furrify-dev
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.furrify.tech/realms/furrify-dev


  datasource:
    driverClassName: org.h2.Driver
    username: 'sa'
    password: 'password'
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka

server:
  port: 7072