logging:
  level:
    web: INFO

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    schema-registry-servers: ${KAFKA_SCHEMA_REGISTRY_SERVERS}
    consumer:
      group-id:
        prefix: "furrifyws-storage-tags-"
    producer:
      retries: 3
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid
            authorization-grant-type: authorization_code
            client-id: ${KEYCLOAK_CLIENT_ID}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  datasource:
    driverClassName: ${DATABASE_DRIVER}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE}

server:
  port: 8080